### PR TITLE
Enhance documentation and set better diagram with some pictures

### PR DESCRIPTION
**Pull request by AhmedBHameed**
Hello @firsttris ,

Hope you are doing well.

May you please review and confirm those changes when you have time ?

All best wishes.

### CODE REVIEW

**Comment by firsttris** [comment]
Hey @AhmedBHameed 

good work, i really appreciate the effort you put in.

here are some advices to your pull-request. you don't have todo this just if you like it ;)

1.) Examples
"For instance, those code can be used to read from your NFC card and log some information on the screen"

would it not be better to this example in the test folder and link it in the readme, so that people can directly run it?
also we would have only one source for those "test's / examples".

what about those others tests are they still valid and useful?
then there is this issue https://github.com/firsttris/mfrc522-rpi/issues/5 with an example of NTAG213, should we maybe update the dumpNTAG213.js file?

2.) Demonstration
i like it, very good.
what do you think about the idea to put pictures of the demonstration in a own Markdown File and link it in the Readme File? Because the Readme tend to get big. 

3.) Video
this is super nice.
it would be even better if we could directly embed the Video, there are two possible ways i could think of

option 1 would be to convert it to a gif and embed it.

option 2 would be upload it somewhere like youtube and make a link [pictureOfVideo](urlToYoutube).

i think most people are to lazy and will not download and play it (to much steps)

**Comment by AhmedBHameed** [comment]
Hello @firsttris ,

1. I agree with you, i removed the example and kept oly links to test. Regarding other test, unfortunately, my chip is only for reading and nu writable chip so not sure how to test those without having writable chip in hand. so i can't verify them :(

2. Yes good idea i spitted them in a separate folder.

3. You can check the link for the video now.

Sorry for those mistakes, my experience with publishing things in development hehe.

Regards.
Ahmed

**Comment by AhmedBHameed** [comment]
Also what do you thing about updating npm docs ? That would also participate in distributions of the module.

**Comment by firsttris** [comment]
npm docs will get updated with git readme once we released a new version

**Comment by firsttris** [comment]
do you think this extended wiring picture will be confusing for newbie users?

https://github.com/firsttris/mfrc522-rpi/raw/docs/wiki/mfrc522-node.png

in comperence to the old one

https://github.com/firsttris/mfrc522-rpi/raw/master/wiki/rpi-mfrc522-wiring2.PNG

i mean if you are new you would probably just connect it to the PI, without buzzer

my understanding is that both options are possible.

would it not be better to put both wiring pictures in the readme?

Saying this one is the simple wiring, and the other is the extended version with buzzer.

**Comment by AhmedBHameed** [comment]
I was thinking the new schema might be easier!!
Hmmm, better to re-think again. Ok will retrieve back the base connection and add some notes for extra buzzer feature.

Thank you for noting.

**Comment by AhmedBHameed** [comment]
I added new schema as optional way for interfacing.

**Comment by firsttris** [comment]
nice sir, i did some polishing as well, are you okay with it?

i would be rdy to merge this

**Comment by AhmedBHameed** [comment]
Sound good for me. Thank you for your nice polish.

**Pull request merged**
