### PR TITLE
Migration from WiringPI to SoftSPI.

### PR DESCRIPTION
**Pull request by firsttris**

### CODE REVIEW

**Comment by Zwimber** [comment]
Why would you prefer SoftSPI?

**Comment by firsttris** [comment]
i just saw that some user migrated it and wanted to test and see how it works, but generally in the past wiring-pi did broke very often (on kernel changes) and the repo is not very active https://github.com/fengjiannan2010/wiringpi-node in comperence to https://github.com/jperkin/node-rpio

**Comment by Bernix01** [comment]
Any update on this?

Ps.: Merge pls.

**Comment by firsttris** [comment]
Have someone tested this and can confirm its working?

i don't have a testing environment running at the moment.

im would be happy to merge if someone can confirm?

**Comment by Fantus** [comment]
Worked for me using the default pins for the pi 3b+

```
'use strict';

const Mfrc522 = require('mfrc522-rpi');
const SoftSPI = require('rpi-softspi');

//# This loop keeps checking for chips. If one is near it will get the UID and authenticate
console.log('scanning...');
console.log('Please put chip or keycard in the antenna inductive zone!');
console.log('Press Ctrl-C to stop.');

const softSPI = new SoftSPI({
    clock:  23, // pin number of SCLK
    mosi:   19, // pin number of MOSI
    miso:   21, // pin number of MISO
    client: 24, // pin number of CS
});
const mfrc522 = new Mfrc522(softSPI, 22);
setInterval(function () {

    //# reset card
    mfrc522.reset();

    //# Scan for cards
    let response = mfrc522.findCard();
    if (!response.status) {
        console.log('No Card');
        return;
    }
    console.log('Card detected, CardType: ' + response.bitSize);

    //# Get the UID of the card
    response = mfrc522.getUid();
    if (!response.status) {
        console.log('UID Scan Error');
        return;
    }
    //# If we have the UID, continue
    const uid = response.data;

    console.log('Card read UID: %s %s %s %s', Buffer.from(uid.slice(0, 4)).toString('hex'));
}, 500);

```

output:
```
scanning...
Please put chip or keycard in the antenna inductive zone!
Press Ctrl-C to stop.
No Card
No Card
No Card
Card detected, CardType: 16
Card read UID: a0d6912f
Card detected, CardType: 16
Card read UID: a0d6912f
Card detected, CardType: 16
Card read UID: a0d6912f
```

**Comment by firsttris** [comment]
thx @Fantus i will merge & release a new version as soon as i find some time

**Comment by firsttris** [comment]
softpi was released this with https://github.com/firsttris/mfrc522-rpi/pull/8 version 2.0.0

**Pull request closed without merging**
