### PR TITLE
I added BUZZER pin functionality.

### PR DESCRIPTION
**Pull request by AhmedBHameed**
To notify the client that his card has been read successfully. when mounted to a real system.

Feel free to give notes. I will correct and push again if needed.

### CODE REVIEW

**Comment by firsttris** [comment]
@AhmedBHameed thats really awesome!

**Comment by firsttris** [comment]
have you seen this other pull-request where some people refactored to rpio (softpi)?
https://github.com/firsttris/mfrc522-rpi/pull/6

would it be possible to migrate your BUZZER Extension to Softpi as well?

reason: we always had problems with wiring-pi not being updated on kernel updates... rpio was updated more regurlarley

**Comment by AhmedBHameed** [comment]
Hello @firsttris , Ok sounds interesting and good idea since the `WiringPI` is also not working with the latest node version. I will take a look and may be update my PR with SoftSPI code.

Till then, have a great day/night

**Comment by AhmedBHameed** [comment]
Hello @firsttris ,
I managed to merge buzzer alert feature to SoftSPI.
Also tested with Raspberry Pi 3 Model B+

Feel free to give review and comments.

**Comment by firsttris** [comment]
@AhmedBHameed 
impressed, very good work! i will release this as 2.0 of mfrc522-rpi

if you like i would add you as contributor?

**Comment by firsttris** [comment]
@AhmedBHameed could you add some more notes to the readme how to connect the buzzer? which buzzer was used, and where to buy them?

**Comment by AhmedBHameed** [comment]
@firsttris ,
That would be nice of you.

Hmmm, Ok will try to open another pull request explaining about it in more details.

**Comment by firsttris** [comment]
@AhmedBHameed 
i already added some more infos to readme.
do you think its sufficient like this ?

https://github.com/firsttris/mfrc522-rpi#buzzer

**Comment by firsttris** [comment]
@AhmedBHameed 
added you as collaborator to the repository, you have full access now

**Comment by AhmedBHameed** [comment]
Hi @firsttris 

I really appreciate your generosity here.

I saw your additional information. Those are enough in case of some experience with a person.
I will add more specific information to make it peace of cake for all people. for example those buzzers have two type the one with 5V DC and the other need extra circuit to produce noise. Also the CARD is working with 3.3 volt and the buzzer is "Better" working with 5V with no sound failure.   

It will take time according to my free time. Bit will keep it in mind.

**Pull request merged**
