### PR TITLE
added support for 7 byte uid

### PR DESCRIPTION
**Pull request by dsl400**
a quick hack to read the 7 byte UID

documentation:
page 4  describes how it works
https://www.nxp.com/docs/en/application-note/AN10927.pdf 
page 32 contains the instruction set bytecodes
https://www.nxp.com/docs/en/data-sheet/NTAG213_215_216.pdf

### CODE REVIEW

**Comment by firsttris** [comment]
hey @dsl400 thx for your work, i appreciate your contribution.

From my knowledge i think you should use "let" only if you want to re-assign new values to the variable after its declaration.
I think in most cases you can use "const".

some variables where you really need "let" => "select", "uidCheck"

regards
Tristan

**Comment by dsl400** [comment]
it is just _a quick hack_
thanks for the feedback :)

**Comment by trgraglia** [comment]
Hi @dsl400 , I have implemented the changes and it does not currently work for a MIFARE DESFire EV2 which is also a 7 byte UID. Was this code working for you with other NFCs with 7 byte UIDs? Was this change "complete"? 
Thanks

**Comment by dsl400** [comment]
> Hi @dsl400 , I have implemented the changes and it does not currently work for a MIFARE DESFire EV2 which is also a 7 byte UID. Was this code working for you with other NFCs with 7 byte UIDs? Was this change "complete"?
> Thanks

I have no Ideea if it works with  MIFARE DESFire EV2, you will have to consult the documentation and see if it needs any changes, just like I did

**Pull request closed without merging**
